### ISSUE TITLE
Globales Wiki dauerhaft und präsenter verlinken

### ISSUE THREAD

**Issue by RobertMischke** [memucho/webapp#123]
Das globale Wiki soll in allen Themen, die nicht im globalen Wiki sind, verlinkt werden.

https://www.figma.com/file/fD6PIAMN305W6NuxP5ldNi/%5Bworksheet%5D?node-id=1441%3A17589

![image](https://user-images.githubusercontent.com/156185/147121103-d287e2eb-5026-41ba-9dc7-83aa935f8fcb.png)

**Comment by feevonderspree** [comment]
@tj-mai: 
In meinem janine account (gmail) fehlt der Globales-Wiki-Chip im persönlichen Wiki. 
Bin ich auf der Startseite anderer Nutzer, ist der Themenchip zu sehen. 
in meinem feevonderspree account (gmx) ist der Chip zu sehen. 

![Bildschirmfoto 2022-01-17 um 17 31 30](https://user-images.githubusercontent.com/96989427/149807761-580d105d-cf64-4c8d-bd2c-0195ba059300.png)

![Bildschirmfoto 2022-01-17 um 17 28 34](https://user-images.githubusercontent.com/96989427/149807751-755d5fa9-0ab2-4ca6-b589-220c6d0478e5.png)

![Bildschirmfoto 2022-01-17 um 17 30 40](https://user-images.githubusercontent.com/96989427/149807754-991ffc24-ee7c-45d2-bb01-dfae83bef353.png)
