### ISSUE TITLE
Responsive: Themenviews und Autoren in einer Zeile

### ISSUE THREAD

**Issue by RobertMischke** [memucho/webapp#125]
Wenn das Ticket abgeschlossen ist, Rückfrage an Janine - mit ein paar Screenshots -, ob sie zufrieden ist. 

![image](https://user-images.githubusercontent.com/156185/147123277-c40b3f49-8f55-4a61-a399-e745798e8359.png)

**Comment by SchwabJustin** [comment]
![image](https://user-images.githubusercontent.com/41286356/150344688-d16b936d-20ee-4b69-bcc5-5f54701d781d.png)
