### ISSUE TITLE
Bearbeitungshistorie: fehlerhafter Eintrag für "Verknüpfung entfernt"

### ISSUE THREAD

**Issue by RobertMischke** [memucho/webapp#143]
In der Bearbeitungshistorie wird angezeigt, dass die Verknüpfung "memucho Wiki" → "Dokumentation" entfernt wurde. Allerdings ist die Verknüpfung noch vorhanden, also "Dokumentation" ist dem "memucho Wiki" noch zugeordnet. Das sieht für mich wie ein Fehler aus. 

![image](https://user-images.githubusercontent.com/156185/147374062-be872daa-4429-4464-96c0-89d718913675.png)

Auch der Eintrag darüber ist fehlerhaft: Die Verknüpfung "Informatik" → "Rechnernetz" wurde nicht entfernt.

**Comment by tj-mai** [comment]
Moegliche Fehlerquelle: #222
