### ISSUE TITLE
Nach Registrierung mit Google/Facebook gibt es eine 404 Seite

### ISSUE THREAD

**Issue by RobertMischke** [memucho/webapp#155]
Nach der Registrierung mit Google kommt man auf eine 404 Seite. 
https://memucho.de/Registrieren

Bitte auch die normale Registrierung prüfen.

**Comment by feevonderspree** [comment]
**facebook Registrierung** problemlos. 
Aber: Anschließende Änderung des Profilnamen und Abmedlung führt zum Aufhängen der Seite. 
War in zweitem Tab als anderer Benutzer angemeldet. Nach dem Schließen des Tabs reload das anderen, offenen Tabs lief alles.

https://user-images.githubusercontent.com/96989427/148037785-0da56630-66a4-4396-b3dd-77ecf9588d49.mp4

**Comment by feevonderspree** [comment]
Registrierung mit Google hat auch außerhalb des Incognito-Tabs nicht funktioniert. 
Bei Änderung der Browser-Einstellungen (Schutz vor Aktivitätenverfolgung), gelange ich ohne Modal direkt auf die Registrieren-Seite (s. Screen) – offensichtlich schon angemeldet.

![Bildschirmfoto 2022-01-03 um 15 57 25](https://user-images.githubusercontent.com/96989427/148038483-c31432f7-e58d-48dc-86a9-cf6a73fdc15f.png)
