### ISSUE TITLE
Neustart einer Lernsitzung erneuert die Frageliste nicht

### ISSUE THREAD

**Issue by tj-mai** [memucho/webapp#158]

**Comment by RobertMischke** [comment]
@tj-mai wie startet man eine Lernsitzung neu?

**Comment by tj-mai** [comment]
lernsitzung beenden indem man durch alle fragen durchgeht > auf der result seite neue lernsitzung starten.

**Comment by RobertMischke** [comment]
Bitte prüfen, ob der Punkte noch aktuell ist, falls ja, bei "Next" recht weit oben einsortieren.
