### ISSUE TITLE
"Zum Ergebnis" funktioniert nicht mehr

### ISSUE THREAD

**Issue by RobertMischke** [memucho/webapp#160]
Der Klick auf "Zum Ergebnis" funktioniert nicht mehr. 

![image](https://user-images.githubusercontent.com/156185/147831246-60c59460-9524-4f28-a9fc-68fbd4538d9c.png)

**Comment by tj-mai** [comment]
kann es weder auf live, stage oder lokal reproduzieren, bitte genaue Schritte angeben.

**Comment by feevonderspree** [comment]
ich kann es ebenfalls nicht mehr reproduzieren, es funktioniert (stage und live gestestet, angemeldet und anonym).
