### ISSUE TITLE
Banner "zur Doku / Alles an einem Ort" anpassen

### ISSUE THREAD

**Issue by feevonderspree** [memucho/webapp#193]
1. Das Wording des Buttons "Jetzt mehr erfahren" im Doku-Banner ist uneindeutig. Das Ziel des Links ist für den Nutzer nicht erkennbar. Das Wording soll geändert werden in: "Zur Dokumentation"
2. Die Schließen-Icons sollen alle die gleiche Größe haben. Die Vorgaben für diesen Banner wurden geändert, bitte anpassen. -> done
3. Das Icon aus dem neuen Entwurf übernehmen.

figma: 
style guide: https://www.figma.com/file/dfUuh7WP1Fl27uZioZ4SyZ/%F0%9F%8E%A8-Design-System-%E2%80%93-UI-Kit?node-id=640%3A91
example screen: https://www.figma.com/file/fD6PIAMN305W6NuxP5ldNi/01-worksheet?node-id=1646%3A24527

![Bildschirmfoto 2022-01-11 um 12 22 57](https://user-images.githubusercontent.com/96989427/148934106-1b043e5d-e53e-4f85-b608-541dd2a8246d.png)

**Comment by feevonderspree** [comment]
@RobertMischke sollen wir hier den Vorschlag für das neue Design mit neuen Icons von openmoji übernehmen? 

![grafik](https://user-images.githubusercontent.com/96989427/149756964-4ac6c69c-8133-4298-9a8e-ac9f4f93f449.png)
![Bildschirmfoto 2022-01-17 um 11 54 56](https://user-images.githubusercontent.com/96989427/149757020-e28ba3bb-8d2f-4207-a110-d548d3c4430b.png)

**Comment by RobertMischke** [comment]
Ich empfinde das Icon als okay. 
Das Icon links bündig machen?
