### ISSUE TITLE
Fehlerhaften Link entfernen

### ISSUE THREAD

**Issue by RobertMischke** [memucho/webapp#199]
![image](https://user-images.githubusercontent.com/156185/148976446-2b8be245-5f13-463a-a859-ff86f748e285.png)

**Comment by feevonderspree** [comment]
@tj-mai: Der Link ist noch drin, wenn ich über den oberen Bereich des Menüs hovere, zeigt der Cursor einen Link an. Bei Klick erfolgt keine Aktion.
