### ISSUE TITLE
Globale Historie wird vom Maintenance Controller überflutet

### ISSUE THREAD

**Issue by tj-mai** [memucho/webapp#218]
Alle Änderungen die an den CategoryRelations durch den Maintenance Controller gemacht werden, werden von den Category Changes vermerkt. Da er jedes Thema manche sogar mehrfach aufruft, kommt es zu einer Überflutung der CategoryChanges. Dies führt dazu dass es nicht korrekt dargestellt werden kann. 

Soll Zustand:
Wenn durch den MaintenanceController Änderungen an Kategorien gemacht werden soll dieses als ein Eintrag in der Historie stehen.

Lösungsvorschläge:
Änderungen durch den MaintenanceController sollten mit der AuthorId 0 oder -1 gemacht werden. Diese kann dann aus den CategoryChanges gefiltert werden. Zusätzlich sollte jede Funktion im MaintenanceController einen neuen Typen (MaintenanceChange) als Change in die Globale Historie eintragen, mit der ausführenden AuthorId und dem Namen der ausgeführten Methode.

**Comment by RobertMischke** [comment]
Grundsätzlich halte ich es für richtig, dass wenn Änderungen erfolgen, diese auch in der Historie erscheinen. In diesem Fall liegt der Fehler eher darin, dass ausschließlich Änderungen von IncludesContentOf gespeichert werden. Hierbei handelt es sich um ein technisches Detail - der Nutzer weiß ja nichts von IncludesContentOf-Relations. 

Daher: Wird nur IncludesContentOf geschrieben, soll keine ChangeHistory geschrieben werden.
