### ISSUE TITLE
Fragentext wird teilweise zentriert dargestellt

### ISSUE THREAD

**Issue by cmauersberger** [memucho/webapp#226]
Bei einer (Karteikarten-)Frage werden manche Absätze zentriert dargestellt (unklar nach welcher Regel, es ist nicht nur der erste Absatz). Ich habe keine Kontrolle über die Ausrichtung beim Erstellen der Frage. Bei zentrierter Darstellung ist der Umbruch vor Satzzeichen auch merkwürdig.
Erwartet: Immer linksbündig oder Kontrolle über Ausrichtung (und standardmäßig links)?

![grafik](https://user-images.githubusercontent.com/10414631/151119718-b3e9a079-d603-48e6-8e62-c0a430875977.png)

**Comment by RobertMischke** [comment]
@cmauersberger, vielen Dank für diesen Issue! :-) Die Umbrüche sind sicher falsch. Es wird nach jedem HTML-Tag umgebrochen. Das soll gefixt werden. / @tj-mai 

Ich habe mir gerade eine größere Menge von Karteikarten auf memucho und auf Quizlet angeschaut. Die mittige Zentrierung funktioniert aus meiner Sicht meist sehr gut und scheint mir ein guter Default zu sein. Den Vorschlag die Bündigkeit zu steuern, habe ich hier erfasst: #239 / @feevonderspree
