### ISSUE TITLE
(Nicht reproduzierbar) Error when changing name of a topic

### ISSUE THREAD

**Issue by cmauersberger** [memucho/webapp#263]
Bug (Firefox at least)
Repro:
- Open a topic page (someone else created?).
- Change the name
Behaviour: 
- An error dialog immediately opens

![grafik](https://user-images.githubusercontent.com/10414631/153553845-afccea42-5a91-4213-80a9-28dc230ed3ad.png)

**Comment by SchwabJustin** [comment]
Hi, 
Der Bug konnte von mir nicht reproduziert werden (Firefox & Chrome). Du hattest das Thema auch erfolgreich umbenannt (siehe Screenshot), trat der Fehler erst danach auf?
![image](https://user-images.githubusercontent.com/41286356/153770450-13474877-e5d2-49a6-bc24-6e08ca7bb1bd.png)

**Comment by RobertMischke** [comment]
Ich schließe das Issue (erstmal), der Fehler konnte nicht reproduziert werden.

@cmauersberger oder hast du den Fehler immer noch?
