### ISSUE TITLE
Unterthemen-Link im Titel funktioniert im Fragetab nicht

### ISSUE THREAD

**Issue by feevonderspree** [memucho/webapp#344]
Der Link zu den Unterthemen funktioniert aus dem Fragetab nicht.
![Bildschirmfoto 2022-04-04 um 10 26 19](https://user-images.githubusercontent.com/96989427/161504557-7a7f86c9-bf11-4db7-8b11-a4d9336591fd.png)

**Comment by RobertMischke** [comment]
Wurde bereits erledigt.
