### ISSUE TITLE
Verknüpfungen mit meinem Wiki ändern auch die öffentlichen Verknüpfungen

### ISSUE THREAD

**Issue by feevonderspree** [memucho/webapp#407]
Ich kann im "Mit meinem Wiki verknüpfen"-Dialog Verknüpfungen mit Themen außerhalb meines Wikis erstellen, z. B. in Roberts Wiki, im memuchoWiki oder sogar im Globalen Wiki. 

Wähle ich im "Mit meinem Wiki Verknüpfen"-Dialog ein öffentliches, mit meinem Wiki verknüpftes Thema als Zielthema, wird das neue verknüpfte Thema nicht nur in meinem Wiki hinzugefügt, sondern auch in dem jeweils öffentlichen Wiki. 

Bsp: 
1. Ich verknüpfe Zertifikate mit meinem p. Wiki
2. Ich gehe zu -> Globales Wiki -> Studium -> Medienwissenschaften -> und klicke "Zu meinem Wiki hinzufügen" im Dreipunkt-Menü
3. Ich wähle als Zielthema "Zertifikate" aus meinem Wiki aus
4. Medienwissenschaften ist nun sowohl in meinem Wiki untterthema von Zertifikate, als auch im Globalen Wiki 

![grafik](https://user-images.githubusercontent.com/96989427/194904223-58bc62c7-2baa-49fb-965f-01f3124292f4.png)
![grafik](https://user-images.githubusercontent.com/96989427/194904257-a85172fe-17bd-4ae4-a35f-7be53768e800.png)
![grafik](https://user-images.githubusercontent.com/96989427/194904284-2a36f08b-1987-4b64-95c6-fbded445941d.png)

**Comment by juletof** [comment]
Das ist kein Bug, sondern das zu erwartende Verhalten. Das Thema Zertifikate, das ich in mein Wiki eingehängt habe, IST das öffentliche Thema, keine Kopie. Insofern ändere ich es auch dann, wenn ich es innerhalb von meinem Wiki bearbeite. Es gibt keine privaten Verküpfungen, nur private Themen. Ein solches Ansinnen kann man gerade nur umsetzen, indem  man ein privates Thema "dazwischenschaltet". Die Aufgabe besteht hier vielmehr darin, die Usability so zu gestalten, dass dem Nutzer klar wird, was er tut. Ich schließe das Issue hier erstmal und erstelle ein neues konzeptionelles mit Verweis auf dieses hier.
